/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import beans.Agenda_Central;
import beans.Item_Agendamento;
import beans.Servico_Disc;
import beans.Tipo_Marc;
import com.sun.glass.events.KeyEvent;
import controller.Agenda_Central_Controller;
import javax.swing.JOptionPane;
import servicos.PreencherCombo;

/**
 *
 * @author administrador
 */
public class TelaAgenda_Central extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agenda_Central
     */
    public TelaAgenda_Central() {
        initComponents();
        jl_texto.setText(texto);
    }
    String texto = "<html> <b><p align=justify>Esta tela é para auxiliar quando acabar o limite de agendamento para determinado tipo de marcação</p><b><html>";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jt_qtde = new javax.swing.JTextField();
        combo_servico = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jt_encaixe = new javax.swing.JTextField();
        jb_alterar = new javax.swing.JButton();
        jb_limpar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jb_pesq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jt_codigo = new javax.swing.JTextField();
        jl_texto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        combo_tipoAgenda = new javax.swing.JComboBox();
        chk_ativo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt_hrRealiza = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jt_qtdeMax = new javax.swing.JTextField();
        jb_alterar1 = new javax.swing.JButton();

        setResizable(true);
        setTitle("Agenda Central");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Serviço:");

        jLabel3.setText("Tipo de Marcação:");

        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        combo_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_servicoActionPerformed(evt);
            }
        });

        jLabel5.setText("Encaixe:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_encaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_qtde, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, 0, 234, Short.MAX_VALUE)
                    .addComponent(combo_servico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jt_qtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jt_encaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jb_alterar.setText("Atualizar Serviço");
        jb_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_alterarActionPerformed(evt);
            }
        });

        jb_limpar.setText("Limpar");
        jb_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limparActionPerformed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jb_pesq.setMnemonic('r');
        jb_pesq.setText("Pesquisar");
        jb_pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pesqActionPerformed(evt);
            }
        });

        jLabel1.setText("Código da Agenda:");

        jt_codigo.setBackground(new java.awt.Color(255, 255, 0));
        jt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_codigoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_pesq))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_pesq)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jl_texto.setForeground(new java.awt.Color(255, 0, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Item Agendamento: ");

        combo_tipoAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoAgendaActionPerformed(evt);
            }
        });

        jLabel7.setText("Hora Realização:");

        jLabel8.setText("Ativo?");

        jLabel9.setText("Quantidade Máxima:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_tipoAgenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(chk_ativo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jt_hrRealiza)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jt_qtdeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_tipoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk_ativo)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jt_hrRealiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_qtdeMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jb_alterar1.setText("Atualizar Item");
        jb_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_alterar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_alterar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_cancelar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_alterar)
                    .addComponent(jb_limpar)
                    .addComponent(jb_cancelar)
                    .addComponent(jb_alterar1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limparActionPerformed
       limpar();    
    }//GEN-LAST:event_jb_limparActionPerformed

    private void jb_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_alterarActionPerformed
       alterar();
    }//GEN-LAST:event_jb_alterarActionPerformed

    private void jb_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pesqActionPerformed
       buscar();
       
    }//GEN-LAST:event_jb_pesqActionPerformed

    private void jt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_codigoKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           jb_pesq.doClick();
       }
    }//GEN-LAST:event_jt_codigoKeyPressed
Agenda_Central_Controller acc = new Agenda_Central_Controller();
Agenda_Central ac = new Agenda_Central();
    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        try{
            buscaComboTipo();
        }catch(Exception e){}
    }//GEN-LAST:event_comboTipoActionPerformed

    private void combo_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_servicoActionPerformed
       try{
           buscaComboServico();
       }  
       catch(Exception e){}
    }//GEN-LAST:event_combo_servicoActionPerformed

    private void combo_tipoAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoAgendaActionPerformed
        try{
            recItemAgenda();
        }catch(Exception e){}
    }//GEN-LAST:event_combo_tipoAgendaActionPerformed

    private void jb_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_alterar1ActionPerformed
       alterarTipoAgendamento();
    }//GEN-LAST:event_jb_alterar1ActionPerformed
   
    private void buscaComboTipo(){
       
       tm = (Tipo_Marc) comboTipo.getSelectedItem();
       
       int marc = tm.getCodigo();
       int serv = sd.getCodigo();
               
       int qtde = acc.qtdeAgenda(Integer.parseInt(jt_codigo.getText()), serv, marc);
       int encaixe = acc.qtdeEncaixe(Integer.parseInt(jt_codigo.getText()), serv, marc);
       jt_qtde.setText(""+qtde);
       jt_encaixe.setText(""+encaixe);
   }
    
    private void buscaComboServico(){
       
       sd = (Servico_Disc) combo_servico.getSelectedItem();
 
       tm = (Tipo_Marc) comboTipo.getSelectedItem();
       
       int marc = tm.getCodigo();
       int serv = sd.getCodigo();
               
       int qtde = acc.qtdeAgenda(Integer.parseInt(jt_codigo.getText()), serv, marc);
       int encaixe = acc.qtdeEncaixe(Integer.parseInt(jt_codigo.getText()), serv, marc);
       jt_qtde.setText(""+qtde);
       jt_encaixe.setText(""+encaixe);
   }
    private void buscar(){
       
       ac = acc.busca(Integer.parseInt(jt_codigo.getText()));
       
       
       PreencherCombo.preencherComboTipoMarc(comboTipo, Integer.parseInt(jt_codigo.getText()));
       PreencherCombo.preencherComboServico(combo_servico, Integer.parseInt(jt_codigo.getText()));
       PreencherCombo.preencherComboTipo(combo_tipoAgenda, Integer.parseInt(jt_codigo.getText()));
       jt_qtde.setText(""+ac.getQtde());
   }
   Servico_Disc sd = new Servico_Disc();
   Tipo_Marc tm = new Tipo_Marc();
    private void alterar(){
          
        sd = (Servico_Disc) combo_servico.getSelectedItem();
        tm = (Tipo_Marc) comboTipo.getSelectedItem();
        int tipoMarc = tm.getCodigo();
        int servico = sd.getCodigo();
       boolean teste = acc.alterar(Integer.parseInt(jt_qtde.getText()),Integer.parseInt(jt_encaixe.getText()), Integer.parseInt(jt_codigo.getText()), servico, tipoMarc );
       if(teste){
           JOptionPane.showMessageDialog(null, "Alterado com suecsso!");
       }
   }
    
    private void alterarTipoAgendamento(){
        Item_Agendamento ia;
        ia = (Item_Agendamento) combo_tipoAgenda.getSelectedItem();
        long itemAgend = ia.getCdItem();
        int cdAgend = Integer.parseInt(jt_codigo.getText());
        int qtde = Integer.parseInt(jt_qtdeMax.getText());
       boolean teste = acc.alterarMax(qtde, cdAgend, itemAgend);
       if(teste){
           JOptionPane.showMessageDialog(null, "Alterado com suecsso!");
       }
   }
    private void limpar(){
    
    jt_codigo.setText("");
    jt_qtde.setText("");
    combo_servico.removeAllItems();
    comboTipo.removeAllItems();
    jt_codigo.requestFocus();
}
private void recItemAgenda(){
    Item_Agendamento ia = new Item_Agendamento();
    Agenda_Central_Controller ace = new Agenda_Central_Controller();
    Item_Agendamento i = (Item_Agendamento) combo_tipoAgenda.getSelectedItem();
    long itemSelecionado = i.getCdItem();
    System.out.println("Codigo do item selecionado: "+itemSelecionado);
    ia = ace.rec_item(itemSelecionado);
    if(ia.getSnAtivo().equals("S")){
        chk_ativo.setSelected(true);
    }else{
        chk_ativo.setSelected(false);
    }
    
    jt_hrRealiza.setText(ia.getHrRealizacao());
    
    jt_qtdeMax.setText(""+acc.qtdeItem(Long.parseLong(jt_codigo.getText()), itemSelecionado));
            
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_ativo;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JComboBox combo_servico;
    private javax.swing.JComboBox combo_tipoAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jb_alterar;
    private javax.swing.JButton jb_alterar1;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_limpar;
    private javax.swing.JButton jb_pesq;
    private javax.swing.JLabel jl_texto;
    private javax.swing.JTextField jt_codigo;
    private javax.swing.JTextField jt_encaixe;
    private javax.swing.JTextField jt_hrRealiza;
    private javax.swing.JTextField jt_qtde;
    private javax.swing.JTextField jt_qtdeMax;
    // End of variables declaration//GEN-END:variables
}
