/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import beans.Setor;
import com.sun.glass.events.KeyEvent;
import controller.Setor_Controller;
import javax.swing.JOptionPane;
import servicos.FuncoesSetor;
import servicos.Maiusculas;

/**
 *
 * @author linux
 */
public class TelaCadSetor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadSetor
     */
    public TelaCadSetor() {
        initComponents();
        jl_aviso.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_setor = new javax.swing.JTextField();
        jb_cadastrar = new javax.swing.JButton();
        jb_limpar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jl_aviso = new javax.swing.JLabel();

        setTitle("Cadastrar Setor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Setor");

        jt_setor.setDocument(new Maiusculas());
        jt_setor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_setorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_setorKeyReleased(evt);
            }
        });

        jb_cadastrar.setText("Cadastrar");
        jb_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarActionPerformed(evt);
            }
        });

        jb_limpar.setText("Limpar");
        jb_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limparActionPerformed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jl_aviso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jl_aviso.setForeground(new java.awt.Color(233, 28, 30));
        jl_aviso.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_cadastrar)
                        .addGap(40, 40, 40)
                        .addComponent(jb_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_cancelar)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_setor, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jl_aviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_setor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cadastrar)
                    .addComponent(jb_limpar)
                    .addComponent(jb_cancelar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limparActionPerformed
        jt_setor.setText("");
        jt_setor.requestFocus();
    }//GEN-LAST:event_jb_limparActionPerformed

    private void jb_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarActionPerformed
        salvar();
    }//GEN-LAST:event_jb_cadastrarActionPerformed

    private void jt_setorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_setorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(!jt_setor.getText().equals("")) 
            jb_cadastrar.doClick();
        }
    }//GEN-LAST:event_jt_setorKeyPressed

    private void jt_setorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_setorKeyReleased
       verifcarNome();
    }//GEN-LAST:event_jt_setorKeyReleased
private void verifcarNome(){
    Setor_Controller sc = new Setor_Controller();
    boolean teste = sc.verificaNome(jt_setor.getText().trim());
    if(teste){
        jl_aviso.setText("O Setor informado já existe. Reveja a lista cadastrada");
        jb_cadastrar.setEnabled(false);
    }
    else{
        jl_aviso.setText("");
        jb_cadastrar.setEnabled(true);
    }
    
    
}
private void salvar(){
    Setor setor = new Setor();
    setor.setNome(jt_setor.getText());
    setor.setQtde(0);
    Setor_Controller sc = new Setor_Controller();
    boolean teste = sc.inserir(setor);
    if(teste){
        int opcao = JOptionPane.showConfirmDialog(null, "Cadastrado com sucesso\n Deseja cadastrar outro?", "Cadastro Efetuado", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(opcao == JOptionPane.YES_OPTION){
            jt_setor.setText("");
            jt_setor.requestFocus();
            
            FuncoesSetor.pesquisar_setor("");
        }else{
            FuncoesSetor.pesquisar_setor("");
            dispose();
            
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_cadastrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_limpar;
    private javax.swing.JLabel jl_aviso;
    private javax.swing.JTextField jt_setor;
    // End of variables declaration//GEN-END:variables
}
