/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import beans.Trava;
import controller.Trava_Controller;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import servicos.Maiusculas;

/**
 *
 * @author CARLOS
 */
public class TelaSessao extends javax.swing.JInternalFrame {
     String parametro = "";
     
    /**
     * Creates new form TelaSessao
     */
    public TelaSessao() {
        initComponents();
        jt_user.setEnabled(false);
        barraRolagemHorizontal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jr_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jb_destravar = new javax.swing.JButton();
        jb_cancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jb_buscar = new javax.swing.JButton();
        jr_travados = new javax.swing.JRadioButton();
        jr_user = new javax.swing.JRadioButton();
        jt_user = new javax.swing.JTextField();
        jr_todos = new javax.swing.JRadioButton();
        jr_ouser = new javax.swing.JRadioButton();

        setResizable(true);
        setTitle("Verificar Bloqueio");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SPID", "SID", "SERIAL", "STATUS", "USUARIO", "MAQUINA", "OUSER", "Data", "AÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(70);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(70);
            tabela.getColumnModel().getColumn(0).setMaxWidth(100);
            tabela.getColumnModel().getColumn(1).setMinWidth(1);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(1);
            tabela.getColumnModel().getColumn(1).setMaxWidth(1);
            tabela.getColumnModel().getColumn(2).setMinWidth(1);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(1);
            tabela.getColumnModel().getColumn(2).setMaxWidth(1);
            tabela.getColumnModel().getColumn(3).setMinWidth(100);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(3).setMaxWidth(200);
            tabela.getColumnModel().getColumn(4).setMinWidth(150);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(4).setMaxWidth(200);
            tabela.getColumnModel().getColumn(5).setMinWidth(200);
            tabela.getColumnModel().getColumn(5).setPreferredWidth(200);
            tabela.getColumnModel().getColumn(5).setMaxWidth(250);
            tabela.getColumnModel().getColumn(6).setMinWidth(150);
            tabela.getColumnModel().getColumn(6).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(6).setMaxWidth(250);
            tabela.getColumnModel().getColumn(8).setMinWidth(200);
            tabela.getColumnModel().getColumn(8).setPreferredWidth(200);
            tabela.getColumnModel().getColumn(8).setMaxWidth(250);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jb_destravar.setText("Destravar");
        jb_destravar.setEnabled(false);
        jb_destravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_destravarActionPerformed(evt);
            }
        });

        jb_cancel.setText("Cancelar");
        jb_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_destravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cancel)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_destravar)
                    .addComponent(jb_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jr_group.add(jr_travados);
        jr_travados.setSelected(true);
        jr_travados.setText("Somente Atravados");

        jr_group.add(jr_user);
        jr_user.setText("Por usuários");
        jr_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_userActionPerformed(evt);
            }
        });

        jt_user.setDocument(new Maiusculas());
        jt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_userActionPerformed(evt);
            }
        });
        jt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_userKeyPressed(evt);
            }
        });

        jr_group.add(jr_todos);
        jr_todos.setText("Todos");
        jr_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_todosActionPerformed(evt);
            }
        });

        jr_group.add(jr_ouser);
        jr_ouser.setText("Ouser");
        jr_ouser.setToolTipText("Equivalente ao dono da sessão");
        jr_ouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_ouserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_buscar)
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jr_travados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jr_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jr_todos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jr_ouser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_travados)
                    .addComponent(jr_user)
                    .addComponent(jr_todos)
                    .addComponent(jr_ouser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_buscar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
        buscar();
        
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jb_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_jb_cancelActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        jb_destravar.setEnabled(true);
        if(evt.getClickCount() > 1){
           destravar();
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jb_destravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_destravarActionPerformed
        verifyLock();
    }//GEN-LAST:event_jb_destravarActionPerformed

    private void jr_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_userActionPerformed
        
        jt_user.setEnabled(true);
        jt_user.requestFocus();
        jt_user.setSelectionStart(0);
        jt_user.setSelectionStart(200);
    }//GEN-LAST:event_jr_userActionPerformed

    private void jt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_userActionPerformed

    private void jt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_userKeyPressed
      if(evt.getKeyChar()==KeyEvent.VK_ENTER){
          jb_buscar.doClick();
      }
    }//GEN-LAST:event_jt_userKeyPressed

    private void jr_ouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_ouserActionPerformed
        
        jt_user.setEnabled(true);
        
        jt_user.requestFocus();
        
        jt_user.setSelectionStart(0);
        jt_user.setSelectionStart(200);
    }//GEN-LAST:event_jr_ouserActionPerformed

    private void jr_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_todosActionPerformed
        jt_user.setEnabled(false);
        
    }//GEN-LAST:event_jr_todosActionPerformed
private void verifyLock(){
    int totalSelectedLine = tabela.getSelectedRowCount();
    if(totalSelectedLine>1){
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja matar sessões?","Confirme",JOptionPane.YES_NO_OPTION);
        if(opcao == JOptionPane.YES_OPTION){
            destravarMulti(totalSelectedLine);
        }
        
    }else{
        destravar();
    }
}
    private void destravar(){
        Trava_Controller tc = new Trava_Controller();
        long sid = Long.parseLong(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        long serial = Long.parseLong(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        boolean teste = tc.matar_sessao(sid, serial);
        if(teste){
            JOptionPane.showMessageDialog(null, "Sessão destravada com sucesso", "Suscesso na operação", JOptionPane.INFORMATION_MESSAGE);
            jb_destravar.setEnabled(false);
        }
    } 
    
    private void destravarMulti(int total){
        Trava_Controller tc = new Trava_Controller();
        int[] linhas = tabela.getSelectedRows();
        for(int i = 0; i < total; i++){
            long sid = Long.parseLong(tabela.getValueAt(linhas[i], 1).toString());
            long serial = Long.parseLong(tabela.getValueAt(linhas[i], 2).toString());
            boolean teste = tc.matar_sessao(sid, serial);
                if(teste){
                    System.out.println("Sessão destravada com sucesso");
                    
                }
        }
        
        DefaultTableModel line = (DefaultTableModel) tabela.getModel();
        line.setNumRows(0);
        jb_destravar.setEnabled(false);
        
    } 
    private void buscar(){
        setCursor(Cursor.getPredefinedCursor(3));
            Trava_Controller tc = new Trava_Controller();
            lista = tc.listar(getRadioSelected());
            preencherTabela();
        setCursor(Cursor.getPredefinedCursor(0));
    
    }

private void preencherTabela(){
    DefaultTableModel linha = (DefaultTableModel) tabela.getModel();
    linha.setNumRows(0);
    
    iterator =  lista.iterator();
    
    while(iterator.hasNext()){
        Trava t = (Trava) iterator.next();
        linha.addRow(new String[]{
            ""+t.getSpid(),
            ""+t.getSid(),
            ""+t.getSerial(),
            t.getActive(),
            t.getUser(),
            t.getMaquina(),
            t.getOuser(),
            t.getData(),
            t.getAction()
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancel;
    private javax.swing.JButton jb_destravar;
    private javax.swing.ButtonGroup jr_group;
    private javax.swing.JRadioButton jr_ouser;
    private javax.swing.JRadioButton jr_todos;
    private javax.swing.JRadioButton jr_travados;
    private javax.swing.JRadioButton jr_user;
    private javax.swing.JTextField jt_user;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    List lista;
    Iterator iterator;
    
    private String getRadioSelected(){
        String par = "";
        if(jr_travados.isSelected()){
            par = " and l.BLOCK > 0 ";
        }else if(jr_user.isSelected()){
            par = " AND S.USERNAME LIKE '%"+jt_user.getText()+"%'";
        }else if(jr_ouser.isSelected()){
             
            par = " AND S.OSUSER LIKE '%"+jt_user.getText()+"%'";
        }else{
            par = "";
        }
        return par;
    }
    
    
    private void barraRolagemHorizontal(){
    
    jScrollPane1.setHorizontalScrollBar(new JScrollBar(0)); 
    tabela.setAutoResizeMode (JTable.AUTO_RESIZE_OFF);
   }
}
