/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.SwingUtilities;
import servicos.AparenciaTela;
import servicos.FuncoesTela;
import servicos.Fundo;

/**
 *
 * @author administrador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        aparencia();
    }
private void aparencia(){
    FuncoesTela at = new FuncoesTela();
    at.install();
    SwingUtilities.updateComponentTreeUI(this); 
    AparenciaTela ap = new AparenciaTela();
    ap.iconeTela(this);
    
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new Fundo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_sair = new javax.swing.JMenuItem();
        jm_fechar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jm_produtos = new javax.swing.JMenuItem();
        jm_usuario = new javax.swing.JMenuItem();
        jm_recepcao = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jm_prescricao = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMAtend = new javax.swing.JMenuItem();
        jm_ordem = new javax.swing.JMenuItem();
        JMSessao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Apoio a Tecnologia de Informação - SATI v2.0 "+TelaLogin.servico);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);

        jMenu1.setText("Arquivo");

        jm_sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jm_sair.setText("Sair");
        jm_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_sairActionPerformed(evt);
            }
        });
        jMenu1.add(jm_sair);

        jm_fechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jm_fechar.setText("Tela de Login");
        jm_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_fecharActionPerformed(evt);
            }
        });
        jMenu1.add(jm_fechar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Problemas");

        jm_produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jm_produtos.setText("Farmácia");
        jm_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_produtosActionPerformed(evt);
            }
        });
        jMenu2.add(jm_produtos);

        jm_usuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jm_usuario.setText("Usuarios");
        jm_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_usuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jm_usuario);

        jm_recepcao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jm_recepcao.setText("Recepção");
        jm_recepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_recepcaoActionPerformed(evt);
            }
        });
        jMenu2.add(jm_recepcao);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Situação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jm_prescricao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jm_prescricao.setText("Prescrição");
        jm_prescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_prescricaoActionPerformed(evt);
            }
        });
        jMenu2.add(jm_prescricao);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Prorrogação");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Agenda Central");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMAtend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMAtend.setText("Atendimentos");
        jMAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtendActionPerformed(evt);
            }
        });
        jMenu2.add(jMAtend);

        jm_ordem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jm_ordem.setText("Ordem de Serviço");
        jm_ordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ordemActionPerformed(evt);
            }
        });
        jMenu2.add(jm_ordem);

        JMSessao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        JMSessao.setText("Sessão Travada");
        JMSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMSessaoActionPerformed(evt);
            }
        });
        jMenu2.add(JMSessao);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_usuarioActionPerformed
        TelaUsuarios tu = new TelaUsuarios();
        desktop.add(tu);
        tu.show();
    }//GEN-LAST:event_jm_usuarioActionPerformed

    private void jm_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_produtosActionPerformed
        TelaDesbloquearProduto tDP = new TelaDesbloquearProduto();
        desktop.add(tDP);
        tDP.show();
    }//GEN-LAST:event_jm_produtosActionPerformed

    private void jm_recepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_recepcaoActionPerformed
       TelaConfrmacao tc = new TelaConfrmacao();
       desktop.add(tc);
       tc.show();
    }//GEN-LAST:event_jm_recepcaoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       TelaSituacaoCirurgia tsc = new TelaSituacaoCirurgia();
       desktop.add(tsc);
       tsc.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jm_prescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_prescricaoActionPerformed
       TelaDeletarPrescricao tsc = new TelaDeletarPrescricao();
       desktop.add(tsc);
       tsc.show();
    }//GEN-LAST:event_jm_prescricaoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaGuia tsc = new TelaGuia();
       desktop.add(tsc);
       tsc.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaAgenda_Central tsc = new TelaAgenda_Central();
       desktop.add(tsc);
       tsc.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jm_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jm_sairActionPerformed

    private void jm_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_fecharActionPerformed
        dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jm_fecharActionPerformed

    private void jMAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtendActionPerformed
        TelaLista_Setor tsc = new TelaLista_Setor();
       desktop.add(tsc);
       tsc.show();
    }//GEN-LAST:event_jMAtendActionPerformed

    private void jm_ordemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ordemActionPerformed
        Tela_Ordem_Servico tos = new Tela_Ordem_Servico();
        desktop.add(tos);
        tos.show();
    }//GEN-LAST:event_jm_ordemActionPerformed

    private void JMSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMSessaoActionPerformed
        TelaSessao tos = new TelaSessao();
        desktop.add(tos);
        tos.show();
    }//GEN-LAST:event_JMSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMSessao;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMAtend;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jm_fechar;
    private javax.swing.JMenuItem jm_ordem;
    private javax.swing.JMenuItem jm_prescricao;
    private javax.swing.JMenuItem jm_produtos;
    private javax.swing.JMenuItem jm_recepcao;
    private javax.swing.JMenuItem jm_sair;
    private javax.swing.JMenuItem jm_usuario;
    // End of variables declaration//GEN-END:variables
    
    private int setMaximizedBounds(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
