/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.conexao.FabricaDeConexao;
import servicos.AparenciaTela;
import servicos.FuncoesTela;

/**
 *
 * @author administrador
 */
public class TelaLogin extends javax.swing.JFrame {
         String login;
         String senha;
         public static String servico;
         String host;
         int tentavia = 0;
                
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        jl_mensagem.setText("");
        jl_mensagem.setVisible(false);
        aparencia();
        
                
    }
private void aparencia(){
    FuncoesTela at = new FuncoesTela();
    at.install();
    SwingUtilities.updateComponentTreeUI(this); 
    AparenciaTela ap = new AparenciaTela();
    ap.iconeTela(this);
    AparenciaTela.teclaEscFrame(this);
    
    
    
}
    private void logarNoSistema(){
    login = jt_usuario.getText();
    senha = String.valueOf(jt_senha.getPassword());
    if(combo_banco.getSelectedIndex()== 0){
        servico = "prdmv";
        host = "10.51.26.60";
    }else{
        servico = "smlmv";
        host = "10.51.26.63";
    }
   
    if(tentavia < 3){
                if(FabricaDeConexao.getConnection(login, senha, servico, host))
                {
                    new TelaPrincipal().setVisible(true);
                    dispose();
                }else{
                    tentavia++;
                    jl_mensagem.setVisible(true);
                    jl_mensagem.setText("Login ou senha errado. Tentativa "+tentavia+" de 3");
                    
                }
    }
    else{
        /********** SE O USUARIO TENTAR MAIS DE TRES VEZES  ***********************/
        JOptionPane.showMessageDialog(null, "Você atingiu o limite de tentativa. Tente novamente mais tarde");
        dispose();
    }
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_banco = new javax.swing.JComboBox();
        jl_mensagem = new javax.swing.JLabel();
        jt_senha = new javax.swing.JPasswordField();
        jb_cancelar = new javax.swing.JButton();
        jb_access = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oracle Logon");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");

        jt_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jt_usuario.setToolTipText("Usuário a ser logado no sistema");
        jt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jt_usuarioFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Banco:");

        combo_banco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_banco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "producao", "simulacao" }));
        combo_banco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_bancoActionPerformed(evt);
            }
        });

        jl_mensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_mensagem.setForeground(new java.awt.Color(255, 0, 0));
        jl_mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_mensagem.setText("Mensagem");

        jt_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jt_senhaFocusGained(evt);
            }
        });
        jt_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_senhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_mensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_usuario)
                            .addComponent(combo_banco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41))
        );

        jb_cancelar.setText("Cancelar");
        jb_cancelar.setToolTipText("Fecha a tela atual");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jb_access.setText("Acessar");
        jb_access.setToolTipText("Clique para acessar o sistema");
        jb_access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_accessActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/db.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_access)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_cancelar)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancelar)
                    .addComponent(jb_access))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_accessActionPerformed
        logarNoSistema();
    }//GEN-LAST:event_jb_accessActionPerformed

    private void jt_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_senhaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jb_access.doClick();
        }
    }//GEN-LAST:event_jt_senhaKeyPressed

    private void combo_bancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_bancoActionPerformed
       if(combo_banco.getSelectedIndex()== 0){
        servico = "prdmv";
           System.out.println("Banco: "+servico);
    }else{
        servico = "smlmv";
        System.out.println("Banco: "+servico);
    }
    }//GEN-LAST:event_combo_bancoActionPerformed

    private void jt_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt_usuarioFocusGained
        jt_usuario.setSelectionStart(0);
        jt_usuario.setSelectionEnd(100);
    }//GEN-LAST:event_jt_usuarioFocusGained

    private void jt_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt_senhaFocusGained
        jt_senha.setSelectionStart(0);
        jt_senha.setSelectionEnd(100);
    }//GEN-LAST:event_jt_senhaFocusGained

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_banco;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_access;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JLabel jl_mensagem;
    private javax.swing.JPasswordField jt_senha;
    private javax.swing.JTextField jt_usuario;
    // End of variables declaration//GEN-END:variables
}
